name: CI

on: workflow_dispatch
#  workflow_call:
#  workflow_dispatch:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]

jobs:
  quality-assurance:
    runs-on: ubuntu-latest

    env:
      DJANGO_DEBUG: 1
      DJANGO_SECRET_KEY: qa-secret-key
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Check Python version
        run: python --version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install -r requirements.txt

      - name: Dependency Checks
        run: |
          pip install safety
          safety check -r requirements.txt

      - name: Static Code Analysis
        run: |
          pip install flake8
          flake8 --exclude settings.py,migrations .

      - name: Security Scanning
        run: |
          pip install bandit
          bandit -r .

      - name: Database Migrations Check
        run: |
          python manage.py makemigrations --check --dry-run

      - name: Run Migrations
        run: python manage.py migrate

      - name: Run Tests
        run: python manage.py test

      - name: Code Coverage
        run: |
          pip install coverage
          coverage run --source='.' manage.py test
          coverage report