name: realease and publish
on: workflow_dispatch
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - name: recupere le code
        uses: actions/checkout@v2
      - name: installation de NODE.JS
        run: sudo apt update && sudo apt install nodejs -y
      - name: installation des dependances
        run: npm ci # ci=clean and install : pour installer de maniere propre toutes les dependances
      - name: Message de fin
        run: echo "ALL DONE !"