name: realease and publish
on: workflow_dispatch
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - name: recupere le code
        uses: actions/checkout@v2
      - name: installation de NODE.JS
#        run: sudo apt update && sudo apt install nodejs -y
        uses: actions/setup-node@v4
      - name: installation des dependances
        run: npm ci # ci=clean and install : pour installer de maniere propre toutes les dependances
      - name: initialisation du user git
        run: |
            git config --global user.email "anicetsiewe@gmail.com"
            git config --global user.name "anicetsiewe@gmail.com"
      - name: Message de fin
        run: echo "ALL DONE !"